/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package travelApp;

import com.sun.org.apache.bcel.internal.generic.Select;
import static java.lang.System.err;
import javax.swing.JOptionPane;

/**
 *
 * @author vince
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        sl_cb.setEnabled(false);
        //ncr_cb.setEnabled(false);
        c_cb.setEnabled(false);
        n_cb.setEnabled(false);
    }
    
    void DontShowAll() {
    try {
        sl_cb.setEnabled(false); // Disable the sl_cb combo box
        //ncr_cb.setEnabled(false); // Disable the ncr_cb combo box
        c_cb.setEnabled(false);   // Disable the c_cb combo box
        n_cb.setEnabled(false);   // Disable the n_cb combo box
    } catch (Exception err) { // Fix the catch block by specifying the Exception type
        JOptionPane.showMessageDialog(HomePage.this, err.getMessage());
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        n_cb = new javax.swing.JComboBox<>();
        sl_cb = new javax.swing.JComboBox<>();
        c_cb = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        sl_btn = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Home Page");

        jLabel2.setText("National Capital Region");

        jLabel3.setText("Northern Luzon");

        jLabel4.setText("Central Luzon");

        jLabel5.setText("South Luzon");

        n_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ilocos Norte", "Ilocos Sur", "La Union", "Pangasinan", "Cagayan", "Isabela", "Nueva Vizcaya", "Quirino", "Abra", "Apayao", "Batanes (a group of islands)", "Kalinga", "Mountain Province" }));

        sl_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Albay", "Camarines Norte", "Camarines Sur", "Catanduanes", "Masbate", "Sorsogon", "Batangas", "Cavite", "Quezon", "Laguna", "Rizal", "Marinduque", "Occidental Mindoro", "Oriental Mindoro", "Palawan", "Romblon" }));

        c_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aurora", "Bataan", "Bulacan", "Nueva Ecija", "Pampanga", "Tarlac", "Zambales" }));

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Northern Luzon");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Central Luzon");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        sl_btn.setText("South Luzon");
        sl_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sl_btnActionPerformed(evt);
            }
        });

        jButton7.setText("NCR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(394, 394, 394)
                        .addComponent(jLabel1)
                        .addGap(278, 278, 278))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(n_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(194, 194, 194)
                                .addComponent(c_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                        .addComponent(jButton7)
                        .addGap(224, 224, 224)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sl_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sl_btn))
                .addGap(178, 178, 178))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(236, 236, 236)
                .addComponent(jLabel2)
                .addGap(216, 216, 216)
                .addComponent(jLabel5)
                .addGap(219, 219, 219))
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(247, 247, 247)
                        .addComponent(jButton1)))
                .addGap(258, 258, 258)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton7)
                            .addComponent(sl_btn)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(n_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sl_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 354, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(135, 135, 135))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        sl_cb.setSelectedIndex(-1);  // Reset the selected item in sl_cb combo box
        //ncr_cb.setSelectedIndex(-1); // Reset the selected item in ncr_cb combo box
        c_cb.setSelectedIndex(-1);   // Reset the selected item in c_cb combo box
        n_cb.setSelectedIndex(-1);   // Reset the selected item in n_cb combo box
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (sl_cb.isEnabled()) {
        int selectedIndex1 = sl_cb.getSelectedIndex();
        switch (selectedIndex1){
            case 0:
                albay a = new albay();
                a.setVisible(true);
                break;
            
            case 1:
                camarines_norte cn = new camarines_norte();
                cn.setVisible(true);
                break;
             
            case 2:
                camarines_sur cs = new camarines_sur();
                cs.setVisible(true);
                break;
                
            case 3:
                catanduanes c = new catanduanes();
                c.setVisible(true);
                break;
                
            case 4:
                masbate m = new masbate();
                m.setVisible(true);
                break;
                
            case 5:
                sorsogon s = new sorsogon();
                s.setVisible(true);
                break;
                
            case 6:
                batangas b = new batangas();
                b.setVisible(true);
                break;
                
            case 7:
                cavite cv = new cavite();
                cv.setVisible(true);
                break;
                
            case 8:
                quezon q = new quezon();
                q.setVisible(true);
                break;
                
            case 9:
                laguna l = new laguna();
                l.setVisible(true);
                break;
                
            case 10:
                rizal r = new rizal();
                r.setVisible(true);
                break;
                
            case 11:
                marinduque mr = new marinduque();
                mr.setVisible(true);
                break;
                
            case 12:
                occidental_mindoro ocm = new occidental_mindoro();
                ocm.setVisible(true);
                break;
                
            case 13:
                oriental_mindoro orm = new oriental_mindoro();
                orm.setVisible(true);
                break;
                
            case 14:
                palawan p = new palawan();
                p.setVisible(true);
                break;
                
            case 15:
                romblon rm = new romblon();
                rm.setVisible(true);
                break;
        }
        }
        else if (n_cb.isEnabled()) {        
        int selectedIndex2 = n_cb.getSelectedIndex();
        switch (selectedIndex2){
            case 0:
                ilocos_norte in = new ilocos_norte();
                in.setVisible(true);
                break;
            
            case 1:
                
                ilocos_sur is = new ilocos_sur();
                is.setVisible(true);
                break;
             
            case 2:
                la_union lu = new la_union();
                lu.setVisible(true);
                break;
                
                
            case 3:
                pangasinan pa = new pangasinan();
                pa.setVisible(true);
                break;
                
            case 4:
                cagayan cy = new cagayan();
                cy.setVisible(true);
                break;
                
            case 5:
                isabela i = new isabela();
                i.setVisible(true);
                break;
                
            case 6:
                nueva_vizcaya nv = new nueva_vizcaya();
                nv.setVisible(true);
                break;
                
            case 7:
                quirino qr = new quirino();
                qr.setVisible(true);
                break;
                
            case 8:
                abra ab = new abra();
                ab.setVisible(true);
                break;
                
            case 9:
                apayao ap = new apayao();
                ap.setVisible(true);
                break;
                
            case 10:
                batanes bt = new batanes();
                bt.setVisible(true);
                break;
                
            case 11:
                kalinga k = new kalinga();
                k.setVisible(true);
                break;
                
            case 12:
                mountain_province mp = new mountain_province();
                mp.setVisible(true);
                break;
              }
        }
        else if (c_cb.isEnabled()) {        
        int selectedIndex3 = c_cb.getSelectedIndex();
        switch (selectedIndex3){
            case 0:
                aurora a = new aurora();
                a.setVisible(true);
                break;
            
            case 1:
                bataan b = new bataan();
                b.setVisible(true);
                break;
             
            case 2:
                bulacan bu = new bulacan();
                bu.setVisible(true);
                break;
                
            case 3:
                nueva_ecija ne = new nueva_ecija();
                ne.setVisible(true);
                break;
                
            case 4:
                pampanga p = new pampanga();
                p.setVisible(true);
                break;
                
            case 5:
                tarlac t = new tarlac();
                t.setVisible(true);
                break;
                
            case 6:
                zambales z = new zambales();
                z.setVisible(true);
                break;
                
              }
        }
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void sl_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sl_btnActionPerformed
        // TODO add your handling code here:
        sl_cb.setEnabled(true);
        //ncr_cb.setEnabled(false); // Disable the ncr_cb combo box
        c_cb.setEnabled(false);   // Disable the c_cb combo box
        n_cb.setEnabled(false);   // Disable the n_cb combo box
    }//GEN-LAST:event_sl_btnActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        sl_cb.setEnabled(false);
       // ncr_cb.setEnabled(true); // Disable the ncr_cb combo box
        c_cb.setEnabled(false);   // Disable the c_cb combo box
        n_cb.setEnabled(false);   // Disable the n_cb combo box
        
        dashboard d = new dashboard();
                d.setVisible(true);
                
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        sl_cb.setEnabled(false);
        //ncr_cb.setEnabled(false); // Disable the ncr_cb combo box
        c_cb.setEnabled(true);   // Disable the c_cb combo box
        n_cb.setEnabled(false);   // Disable the n_cb combo box
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        sl_cb.setEnabled(false);
        //sl_cb.setVisible(false);
        
        
        //
        
        //ncr_cb.setEnabled(false); // Disable the ncr_cb combo box
        
        
        c_cb.setEnabled(false);   // Disable the c_cb combo box
        
        
        n_cb.setEnabled(true);   // Disable the n_cb combo box
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> c_cb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JComboBox<String> n_cb;
    private javax.swing.JButton sl_btn;
    private javax.swing.JComboBox<String> sl_cb;
    // End of variables declaration//GEN-END:variables
}
